### ISSUE TITLE
`\` instead of `@` as first character doesnt work

### ISSUE THREAD

**Issue by isak102** [Fildo7525/pretty_hover#1]
This is my config:
```lua
return {
  lazy = false,
  "Fildo7525/pretty_hover",
  config = function()
    require("pretty_hover").setup({
      line = {
        "@brief",
      },
      word = {
        "@param",
        "\\param",
        "@param",
        "@tparam",
        "@see",
      },
      header = {
        "@class",
      },
      stylers = {
        line = "**",
        word = "`",
        header = "###",
      },
      border = "rounded",
    })
  end
}
```

And this is the function documentation for the function im trying to hover: 
```c
/// Create a new heap with bytes total size (including both spaces
/// and metadata), meaning strictly less than bytes will be
/// available for allocation.
///
/// \param bytes the total size of the heap in bytes
/// \param unsafe_stack true if pointers on the stack are to be considered unsafe pointers
/// \param gc_threshold the memory pressure at which gc should be triggered (1.0 = full memory)
/// \return the new heap
heap_t *h_init(size_t bytes, bool unsafe_stack, float gc_threshold);
```

And this is how it looks: 
![image](https://user-images.githubusercontent.com/90389894/230786682-1076d0aa-145f-4dae-827e-1cd2300ed630.png)

As you can see, the `\param` lines are not being highlighted properly. If I change the lines to start with `@param` everything works as expected. Otherwise a really cool plugin, great job

**Comment by Fildo7525** [comment]
Try to fetch changes it should work now.

**Comment by isak102** [comment]
Now the hover just displays this 
![image](https://user-images.githubusercontent.com/90389894/230797302-5a96815b-ce6c-4f9f-8bf4-f4e4ec47268e.png)

**Comment by Fildo7525** [comment]
Can you state the steps to reproduce I tied it multiple times and I did not get this kind of popup.

**Comment by Fildo7525** [comment]
I found that this was happening only with the '\' prefix. I did a small refactor that shouldn't affect this, although it fixed it. Can you confirm it?

**Comment by isak102** [comment]
It still doesn't work for me, I still get the popup just saying `markdown`. The steps I am doing is opening the file, putting my cursor on the `h_init` function and calling `:lua require('pretty_hover').hover()`

**Comment by Fildo7525** [comment]
Fixed it. The Java fix I added caused false parsing of the contents as a table.
